# mr2_rover_description/config/controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    rover_controller:
      type: mr2_rover_control/TwistToCommandsController
    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rover_controller:
  ros__parameters:
    wheel_joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint
    steering_joints:
      - fl_steering_joint
      - fr_steering_joint
      - rl_steering_joint
      - rr_steering_joint
    wheel_base: 0.94
    track_width: 0.65
    wheel_radius: 0.11
    max_steer: 0.6
    twist_timeout: 0.5
    cmd_vel_topic: /cmd_vel

manipulator_controller:
  ros__parameters:
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
