controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_position_controller:
      type: position_controllers/JointPositionController

joint_position_controller:
  ros__parameters:
    joint: joint1

