ARG BASE_IMAGE
FROM ${BASE_IMAGE:-ros:humble}

RUN apt-get update
RUN apt-get install -y build-essential curl git lsb-release gnupg

# Fill in id and token from the curl command on your fleet page.
RUN curl -sf "https://install.transitiverobotics.com?id=ryan000502&token=6p3fd2s1q4x5l4e5n3y1z6x&docker=true" | bash

WORKDIR /transitive-preinstalled

# Optional: pre-configure + pre-install desiredPackages
COPY config.json .

# Optional: env vars (ROS_DOMAIN_ID, etc.)
# COPY .env_user .

WORKDIR /root
COPY entrypoint.sh .
CMD ["./entrypoint.sh"]
