<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mr2_launch</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="gmmyung@kaist.ac.kr">mr2</maintainer>
  <license>MIT</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>aruco_opencv</exec_depend>
  <exec_depend>mr2_video_streaming</exec_depend>
  <exec_depend>mr2_panorama</exec_depend>
  <exec_depend>mr2_science_module</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>socat</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>topic_tools</exec_depend>
  <exec_depend>ublox_dgnss</exec_depend>
  <exec_depend>ublox_dgnss_node</exec_depend>
  <exec_depend>ublox_nav_sat_fix_hp_node</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
