topics:
  # Bridge Gazebo world clock; remap to /clock in launch
  # Force QoS to best effort to match gz clock publishing
  - name: /world/empty_world/clock
    ros_type: rosgraph_msgs/msg/Clock
    gz_type: gz.msgs.Clock
    qos:
      reliability: best_effort
      durability: volatile
  - name: /left_gnss/navsat
    ros_type: sensor_msgs/msg/NavSatFix
    gz_type: gz.msgs.NavSat
  - name: /right_gnss/navsat
    ros_type: sensor_msgs/msg/NavSatFix
    gz_type: gz.msgs.NavSat
  - name: /rgbd_camera/camera_info
    ros_type: sensor_msgs/msg/CameraInfo
    gz_type: gz.msgs.CameraInfo
  - name: /rgbd_camera/depth_image
    ros_type: sensor_msgs/msg/Image
    gz_type: gz.msgs.Image
  - name: /rgbd_camera/image
    ros_type: sensor_msgs/msg/Image
    gz_type: gz.msgs.Image
  - name: /rgbd_camera/points
    ros_type: sensor_msgs/msg/PointCloud2
    gz_type: gz.msgs.PointCloudPacked
  - name: /imu/data
    ros_type: sensor_msgs/msg/Imu
    gz_type: gz.msgs.IMU
