###############################################
# MoveIt Servo parameters for the MR2 manipulator
###############################################

publish_period: 0.02            # seconds between command publications (50 Hz)
max_expected_latency: 0.1       # delay between sending a command and the robot executing it [s]

command_in_type: "speed_units"  # "unitless" or "speed_units"
scale:
  linear: 0.2       # m/s (only used if command_in_type=="unitless")
  rotational: 0.8   # rad/s (only used if command_in_type=="unitless")
  joint: 0.6        # rad/s (only used if command_in_type=="unitless")

command_out_type: std_msgs/Float64MultiArray
command_out_topic: /manipulator_controller/commands
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

use_smoothing: true
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

is_primary_planning_scene_monitor: true
check_octomap_collisions: false

move_group_name: manipulator
planning_frame: base_link
ee_frame_name: eef_link
robot_link_command_frame: base_link

lower_singularity_threshold: 60.0
hard_stop_singularity_threshold: 120.0
leaving_singularity_threshold_multiplier: 2.5
joint_limit_margin: 0.06

cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status

check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.02
scene_collision_proximity_threshold: 0.03
