#!/usr/bin/env python3
"""Render or explicitly install MR2 base-local chrony configuration."""

from __future__ import annotations

import argparse
import ipaddress
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from typing import Callable, Sequence


DEFAULT_TARGET = Path("/etc/chrony/chrony.conf")
RunCommand = Callable[..., subprocess.CompletedProcess[str]]


def valid_host_ipv4(value: str, label: str) -> ipaddress.IPv4Address:
    try:
        address = ipaddress.IPv4Address(value)
    except ipaddress.AddressValueError as exc:
        raise ValueError(f"{label} must be a valid IPv4 address") from exc
    if address.is_unspecified or address.is_multicast or address.is_loopback:
        raise ValueError(f"{label} must be a usable non-loopback unicast IPv4 address")
    return address


def common_config(role: str, base_ip: ipaddress.IPv4Address) -> list[str]:
    return [
        "# Generated by MR2 scripts/latency/chrony/configure_chrony.py",
        f"# Role: {role}; base local reference: {base_ip}",
        "# Replace this complete file through the generator; do not add pool sources.",
        "",
        "driftfile /var/lib/chrony/chrony.drift",
        "rtcsync",
        "logdir /var/log/chrony",
        "log tracking measurements statistics",
        "",
    ]


def render_base_config(base_ip: str, rover_ip: str) -> str:
    base = valid_host_ipv4(base_ip, "base_ip")
    rover = valid_host_ipv4(rover_ip, "rover_ip")
    if base == rover:
        raise ValueError("base_ip and rover_ip must be different")
    lines = common_config("base", base)
    lines.extend(
        [
            "# Serve the base system clock even without Internet or GNSS time.",
            "local stratum 8",
            f"allow {rover}/32",
            "",
            "# Keep chronyc monitoring local to this host.",
            "bindcmdaddress 127.0.0.1",
            "bindcmdaddress ::1",
            "",
        ]
    )
    return "\n".join(lines)


def render_rover_config(base_ip: str) -> str:
    base = valid_host_ipv4(base_ip, "base_ip")
    lines = common_config("rover", base)
    lines.extend(
        [
            "# The base is intentionally the rover's only time source.",
            f"server {base} iburst prefer trust minpoll 2 maxpoll 4",
            "",
            "# Step only during the first updates after chronyd starts.",
            "makestep 0.1 10",
            "",
            "# Keep chronyc monitoring local to this host.",
            "bindcmdaddress 127.0.0.1",
            "bindcmdaddress ::1",
            "",
        ]
    )
    return "\n".join(lines)


def render_config(role: str, base_ip: str, rover_ip: str | None) -> str:
    if role == "base":
        if rover_ip is None:
            raise ValueError("--rover-ip is required for the base role")
        return render_base_config(base_ip, rover_ip)
    if role == "rover":
        if rover_ip is not None:
            raise ValueError("--rover-ip is only valid for the base role")
        return render_rover_config(base_ip)
    raise ValueError(f"unsupported role: {role}")


def write_candidate(path: Path, content: str, force: bool) -> None:
    path = path.resolve()
    if path.exists() and not force:
        raise FileExistsError(f"refusing to overwrite {path}; pass --force")
    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    if not force:
        flags |= os.O_EXCL
    descriptor = os.open(path, flags, 0o644)
    with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
        stream.write(content)


def install_config(
    content: str,
    target: Path = DEFAULT_TARGET,
    chronyd: str = "chronyd",
    service: str = "chrony.service",
    runner: RunCommand = subprocess.run,
    require_root: bool = True,
) -> Path | None:
    if require_root and os.geteuid() != 0:
        raise PermissionError("--install must be run as root")

    target = target.resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    backup: Path | None = None
    target_metadata = target.stat() if target.exists() else None
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=target.parent,
        prefix=".mr2-chrony-",
        delete=False,
    ) as candidate:
        candidate.write(content)
        candidate_path = Path(candidate.name)

    try:
        os.chmod(candidate_path, 0o644)
        runner(
            [chronyd, "-p", "-f", str(candidate_path)],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if target_metadata is not None:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            backup = target.with_name(f"{target.name}.mr2-backup-{timestamp}")
            suffix = 1
            while backup.exists():
                backup = target.with_name(
                    f"{target.name}.mr2-backup-{timestamp}-{suffix}"
                )
                suffix += 1
            shutil.copy2(target, backup)
            os.chmod(candidate_path, stat.S_IMODE(target_metadata.st_mode))
            if (
                candidate_path.stat().st_uid != target_metadata.st_uid
                or candidate_path.stat().st_gid != target_metadata.st_gid
            ):
                os.chown(candidate_path, target_metadata.st_uid, target_metadata.st_gid)

        os.replace(candidate_path, target)
        try:
            runner(
                ["systemctl", "restart", service],
                check=True,
                capture_output=True,
                text=True,
                timeout=20,
            )
        except Exception:
            if backup is not None:
                shutil.copy2(backup, target)
            else:
                target.unlink(missing_ok=True)
            runner(
                ["systemctl", "restart", service],
                check=False,
                capture_output=True,
                text=True,
                timeout=20,
            )
            raise
        return backup
    finally:
        candidate_path.unlink(missing_ok=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--role", choices=("base", "rover"), required=True)
    parser.add_argument("--base-ip", required=True)
    parser.add_argument("--rover-ip")
    destination = parser.add_mutually_exclusive_group()
    destination.add_argument("--output", type=Path)
    destination.add_argument("--install", action="store_true")
    parser.add_argument("--force", action="store_true", help="overwrite --output")
    parser.add_argument(
        "--target", type=Path, default=DEFAULT_TARGET, help=argparse.SUPPRESS
    )
    parser.add_argument("--chronyd", default="chronyd", help=argparse.SUPPRESS)
    parser.add_argument("--service", default="chrony.service", help=argparse.SUPPRESS)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.force and args.output is None:
        parser.error("--force is only valid with --output")
    try:
        content = render_config(args.role, args.base_ip, args.rover_ip)
        if args.install:
            backup = install_config(
                content,
                target=args.target,
                chronyd=args.chronyd,
                service=args.service,
            )
            print(f"Installed {args.role} chrony configuration at {args.target}")
            if backup is not None:
                print(f"Previous configuration backup: {backup}")
                print(
                    f"Rollback: cp {backup} {args.target} && "
                    f"systemctl restart {args.service}"
                )
            print(f"Verify with: chronyc tracking && chronyc sources -v")
        elif args.output is not None:
            write_candidate(args.output, content, args.force)
            print(f"Wrote {args.output}")
        else:
            sys.stdout.write(content)
        return 0
    except (FileExistsError, OSError, subprocess.SubprocessError, ValueError) as exc:
        print(f"configure_chrony: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
