navsat_transform_node:
  ros__parameters:
    # Parameters
    frequency: 20.0 # Same as ekf, but probably slower
    delay: 10.0 # Do it right away...?
    magnetic_declination_radians: 0.2305579942 # Value depends on where you are
    yaw_offset: 0.0 # XXX IMU should give yaw=0 facing East. If not, add offset to measured for desired value.
    zero_altitude: false # Do not set height to 0
    publish_filtered_gps: true # Publish msg sensor_msgs/NavSatFix of world_frame back to GPS coordinate on topic /gps/filtered
    broadcast_utm_transform: true # tf: gps_north_link -> UTM
    use_odometry_yaw: false # 
    wait_for_datum: false # Don't wait to initilaize (datum is about ellipsoid earth)
    # broadcast_utm_transform_as_parent_frame: # We do not use UTM grid (for now)
    transform_timeout: 0.5
    
    gps_frame: gps_north_link
    base_link_frame: base_link
    imu0: /imu/data
    odometry_topic: /odometry/gps
    gps_topic: /rover_north/fix
    
    # Subscribed Topics
    # msg imu/data -> for yaw
    # msg odometry/filtered (nav_msgs/Odometry; estimated from ekf);
    # msg gps/fix
    
    # Published Topics
    # odometry/gps: world frame robot coordinate from GPS coordinate
    # gps/filtered: robot coordinate in GPS coordinate
        