<?xml version="1.0"?>
<package format="3">
  <name>mr2_sik_bridge</name>
  <version>0.1.0</version>
  <description>ROS 2 bridge node for MR2 SiK serial protocol.</description>
  <maintainer email="todo@example.com">TODO</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>mr2_battery_monitor</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
