<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="rover_base" params="length:=0.73 width:=0.49 height:=0.19 mass:=10 rocker_size:=0.1 rocker_mass:=0.5 joint_effort:=50 joint_vel:=2.0 joint_lim:=1.57 front_camera_pitch:=0.3491">

    <link name="base_link">
      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${mass*(width*width + height*height)/12.0}" iyy="${mass*(length*length + height*height)/12.0}" izz="${mass*(length*length + width*width)/12.0}" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin xyz="0 0 ${height/2.0}"/>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin xyz="0 0 ${height/2.0}"/>
      </collision>
    </link>

    <link name="left_rocker">
      <inertial>
        <origin xyz="0 -${width/2.0} 0"/>
        <mass value="${rocker_mass}"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
      </inertial>
      <visual>
        <geometry>
          <box size="${rocker_size} ${rocker_size} ${rocker_size}"/>
        </geometry>
        <origin xyz="0 0 ${rocker_size/2.0}"/>
      </visual>
      <collision>
        <geometry>
          <box size="${rocker_size} ${rocker_size} ${rocker_size}"/>
        </geometry>
        <origin xyz="0 0 ${rocker_size/2.0}"/>
      </collision>
    </link>

    <joint name="left_rocker_joint" type="revolute">
      <parent link="base_link"/>
      <child link="left_rocker"/>
      <origin xyz="0 -${width/2.0} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.0"/>
      <limit lower="-${joint_lim}" upper="${joint_lim}" effort="${joint_effort}" velocity="${joint_vel}"/>
    </joint>

    <link name="right_rocker">
      <inertial>
        <origin xyz="0 ${width/2.0} 0"/>
        <mass value="${rocker_mass}"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
      </inertial>
      <visual>
        <geometry>
          <box size="${rocker_size} ${rocker_size} ${rocker_size}"/>
        </geometry>
        <origin xyz="0 0 ${rocker_size/2.0}"/>
      </visual>
      <collision>
        <geometry>
          <box size="${rocker_size} ${rocker_size} ${rocker_size}"/>
        </geometry>
        <origin xyz="0 0 ${rocker_size/2.0}"/>
      </collision>
    </link>

    <joint name="right_rocker_joint" type="revolute">
      <parent link="base_link"/>
      <child link="right_rocker"/>
      <origin xyz="0 ${width/2.0} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.0"/>
      <limit lower="-${joint_lim}" upper="${joint_lim}" effort="${joint_effort}" velocity="${joint_vel}"/>
      <mimic joint="left_rocker_joint" multiplier="-1" offset="0"/>
    </joint>

    <joint name="right_rocker_joint_mimic" type="fixed">
      <parent link="base_link" />
      <child link="dummy_link" />
    </joint>

    <link name="dummy_link"/>

    <link name="left_gnss"/>
    <joint name="base_to_left_gnss" type="fixed">
      <origin xyz="0 ${-width/2.0} 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="left_gnss"/>
    </joint>

    <link name="right_gnss"/>
    <joint name="base_to_right_gnss" type="fixed">
      <origin xyz="0 ${width/2.0} 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="right_gnss"/>
    </joint>

    <link name="front_camera"/>
    <joint name="base_to_front_camera" type="fixed">
            <origin xyz="${length/2.0} 0 ${height}" rpy="0 ${front_camera_pitch} 0"/>
      <parent link="base_link"/>
      <child link="front_camera"/>
    </joint>

    <!-- IMU mounted at the top of the base box -->
    <link name="imu_link"/>
    <joint name="base_to_imu" type="fixed">
      <origin xyz="0 0 ${height}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="imu_link"/>
    </joint>


  </xacro:macro>
</robot>
